theme: jekyll-theme-slate
title: [The Pólya Urn]
description: [This website will briefly introduce what a Pólya urn is, the long-term behavior of a Pólya Urn, and its correlation with Beta distribution.]
